version: '3'

services:
  redis:
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379
    container_name: redis
    networks:
      - reconnection-service-network-dev
    volumes:
      - redis_data:/data

  frequency:
    image: dsnp/instant-seal-node-with-deployed-schemas:latest
    # We need to specify the platform because it's the only image
    # built by Frequency at the moment, and auto-pull won't work otherwise
    platform: linux/amd64
    # Uncomment SEALING_MODE and SEALING_INTERVAL if you want to use interval sealing.
    # Other options you may want to add depending on your test scenario.
    environment:
      - SEALING_MODE=interval
      - SEALING_INTERVAL=3
    #   - CREATE_EMPTY_BLOCKS=true
    # Uncomment below if you want to let the chain run and keep all of the historical blocks
    command: --state-pruning=archive
    ports:
      - 9944:9944
    networks:
      - reconnection-service-network-dev
    volumes:
      - chainstorage:/data

  webhook:
    container_name: webhook
    hostname: webhook
    build:
      context: webhook-specification/mock-webhook-server
    ports:
      - 3001:3001
    environment:
      NODE_ENV: production
    volumes:
      - ./webhook-specification/mock-webhook-server/responses:/app/responses
    networks:
      - reconnection-service-network-dev

  reconnection-service:
    depends_on:
      - redis
      - frequency
      - webhook
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.docker.dev
    volumes:
      - ./:/app
    networks:
      - reconnection-service-network-dev

volumes:
  redis_data:
  chainstorage:
    external: false

networks:
  reconnection-service-network-dev:
