FROM node:18-alpine3.17

WORKDIR /app
COPY package*.json ./
RUN npm install

# Build / Copy the rest of the application files to the container and build
COPY . .
RUN npm run build

# Start the application
CMD [ "npm", "start" ]
